### ISSUE TITLE
Generated PDF cloud download links yield "Bad Request. Invalid parameters

### ISSUE THREAD

**Issue by gbnewby** [gutenbergtools/autocat3#127]
A reader reported this problem and I've verified with a couple of books. The cloud downloads for generated PDFs yield an error.

Visit these links, for example, then select any of the cloud link icons (Dropbox, GDrive, Onedrive): 

https://www.gutenberg.org/ebooks/22193
https://www.gutenberg.org/ebooks/41511

**Comment by eshellman** [comment]
it appears this was never configured. should be an easy fix

**Comment by eshellman** [comment]
this is fixed. it was difficult to test, because (google) redirects to www from dev, and www issues a new session id, preventing resulting in a 400 error. I used modheader to replay the request with the dev cookie, and it worked.

**Comment by eshellman** [comment]
while close once tested on production

**Comment by eshellman** [comment]
tested on production. Noticed that when logged in to dropbox, Chrome prevents sending to dropbox with 3rd party cookies disabled. This is a recent change in browser behavior that we should look into if people complain. possibly we need some extra text. But bottom line, save to dropbox and to google drive now work for pdf files. did not test the microsoft thing as I don't use MSDrive except for testing.
